### ISSUE TITLE
VnV Review

### ISSUE THREAD

**Issue by rnorouziani** [rnorouziani/Helmholtz-Coil-Current-Calculator-CAS741#11]
Dear Dr. Smith,
The [VnV ](https://github.com/rnorouziani/Helmholtz-Coil-Current-Calculator-CAS741/blob/main/docs/VnVPlan/VnVPlan.pdf) has been added to the repository. Would you please review it?

**Comment by smiths** [comment]
[Reyhaneh_VnVPlan.pdf](https://github.com/rnorouziani/Helmholtz-Coil-Current-Calculator-CAS741/files/14566786/Reyhaneh_VnVPlan.pdf)
