### ISSUE TITLE
VnV Review

### ISSUE THREAD

**Issue by rnorouziani** [rnorouziani/Helmholtz-Coil-Current-Calculator-CAS741#12]
Dear Tanya,
The [VnV ](https://github.com/rnorouziani/Helmholtz-Coil-Current-Calculator-CAS741/blob/main/docs/VnVPlan/VnVPlan.pdf)has been added to the repository. Would you please review it?

**Comment by tanya-jp** [comment]
@rnorouziani 
Hi Reyhaneh,

Thank you for assigning the issue to me. I've reviewed your document and noted a few minor areas for improvement. Overall, your document is excellently written!

Best regards,
Tanya
