### ISSUE TITLE
SRS slides added

### ISSUE THREAD

**Issue by rnorouziani** [rnorouziani/Helmholtz-Coil-Current-Calculator-CAS741#2]
Dear Dr. Smith,
The [slides](https://github.com/rnorouziani/Helmholtz-Coil-Current-Calculator-CAS741/blob/main/docs/Presentations/SRS/SRS.pptx) for today's presentation have been added to the project repository.

**Comment by smiths** [comment]
Here is some quick feedback @rnorouziani:

- include units on slide 3
- I thought you would start from Maxwell's laws as the most abstract theoretical models and then specialize them for the specific case of the Helmholtz coil system.  Is that something that would be feasible for you?
- For the goals can the three currents be calculated independently?  Even if they can, it feels more like one goal than three separate ones.  Calculating all the currents feels like the goal in your case.
